name: Test Action
description: Runs a test action on bash
runs:
  using: composite
  steps:
    - name: Bash echo
      shell: bash
      run: echo Test Action
    - name: New Step
      env:
        ECHO_STRING: 'Echo'
      run: echo $ECHO_STRING $${{github.agent}}
      shell: bash