name: Test Action
description: Runs a test action on bash
branding:
  color: yellow
  icon: command
runs:
  using: composite
  steps:
    - name: Bash echo
      shell: bash
      run: echo Test Action
      id: bash-echo
    - name: New Step
      id: new-step
      env:
        ECHO_STRING: 'Echo'
      run: echo $ECHO_STRING ${{github.actor}} ${{steps.bash-echo}}
      shell: bash
    - name: Another Action
      uses: ./.github/actions/testjs
      with:
        world: 'Hey World from action test-action'