name: Test Action
description: Runs a test action on bash
branding:
  color: green
  icon: credit-card
inputs:
  test:
    required: true
    description: 'sdsdsdasd'
  test2:
    description: "Test 2"
    required: true
runs:
  using: composite
  steps:
    - name: Bash echo
      shell: bash
      run: echo Test Action
      id: bash-echo
    - name: New Step
      id: new-step
      env:
        ECHO_STRING: 'Echo'
      run: echo $ECHO_STRING ${{github.actor}} ${{steps.bash-echo}}
      shell: bash
    - name: Another Action
      uses: ./.github/actions/testjs
      with:
        world: 'Hey World from action test-action'
        world1: 'Hey world 1'