name: cyclic-workflow.yml
on:
  push:
    branches:
      - main
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: job1
        shell: sh
        run: | 
          echo 'job 1'
  job2:
    name: job2
    runs-on: ubuntu-latest
    needs:
      - job3
      - job4
    steps:
      - name: job2
        shell: sh
        run: |
          echo 'job 2'
  job3:
    name: job3
    runs-on: ubuntu-latest
    needs:
      - job4
      - job5
    steps:
      - name: job3
        shell: sh
        run: |
          echo 'job 3'
  job4:
    name: job4
    runs-on: ubuntu-latest
    needs:
      - job5
    steps:
      - name: job4
        shell: sh
        run: |
          echo 'job 4'
  job5:
    name: job5
    runs-on: ubuntu-latest
    steps:
      - name: job5
        shell: sh
        run: |
          echo 'job 5'
