
on:
  fork:
  push:
    branches:
      - main
jobs:
  Checkout:
    name: 'Git Checkout'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          show-progress: true
      - name: Install node packages
        run: |
          npm install @actions/core
          npm install @actions/github
      - name: Echo
        uses: ./.github/actions/test-action
        with:
          test: 'Echo test 1'
          test2: 'Echo test 2'
          input3: ''
      - name: Echo2
        uses: ./src/main/resources/actions/hello
      - name: Test JS Action
        uses: ./.github/actions/testjs
        with:
          world: 'JS World'
          world1: ''
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: 'x64'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package

