on:
  push:
    branches:
      - main
jobs:
  Checkout:
    name: 'Git Checkout'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true
          show-progress: true
      - name: Echo
        uses: actions/test-action
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package

